### PR TITLE
Bump to 0.0.86

### PR DESCRIPTION
**Pull request by jmcriffey**
Tests still pass locally.

### CODE REVIEW

**Comment by mciparelli** [comment]
we could just remove the devDep instead, right?

**Comment by jmcriffey** [comment]
Since traceur still introduces breaking changes every now and then to their API, it might be best to keep it pinned.

**Comment by mciparelli** [comment]
We already made the decision to no longer pin to a specific version after [this discussion](https://github.com/aaronfrost/grunt-traceur/issues/33) so this devDep makes no sense in the plugin I think.

**Comment by jmcriffey** [comment]
Makes sense @mciparelli, I just removed the dev dep instead. We should be able to move forward by changing the peer dep if there is a breaking change down the road.

**Pull request merged**
